<?php

return

  [
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
    [
      "title" => "Laravel migration seeder",
      "description" => "Creiamo una tabella trains tramite la relativa Migration. Ogni treno dovrà avere: Azienda, Stazione di partenza, Stazione di arrivo, Orario di partenza, Orario di arrivo, Codice Treno, Numero Carrozze, In orario, Cancellato. È probabile che siano necessarie altre colonne per far funzionare la tabella nel modo corretto. Inserite inizialmente i dati tramite PhpMyAdmin. Create Model relativo ed un Controller per mostrare nella home page tutti i treni che sono in partenza dalla data odierna. Bonus: Create una seconda migration per aggiungere/modificare una colonna della tabella",
      "repository" => "laravel-migration-seedere",
      "date_create" => "2024-03-23",
      "last_update" => "2024-03-23",
      "author" => "Luca",
    ],
  ];
